//18
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("0.1.2.18")]
[assembly: AssemblyVersion("0.1.2.0")]

namespace Foundations
{
	public static class Version
	{
		public const int major = 0;
		public const int minor = 1;
		public const int patch = 2;
		public const int build = 0;
		public const string Number = "0.1.2.0";
#if DEBUG
		public const string Text = Number + " DEBUG";
#else
		public const string Text = Number + "";
#endif
	}
}